services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    networks:
      - obs_solution_network

networks:
  obs_solution_network:
    driver: bridge
